Fixing a tiny thing

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -8,10 +8,15 @@
 #	- The path to the SSH private key that scp uses
 #
 
-if [ "$4" ] ; then
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
-elif [ "$3" ] ; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
-else
+if [ $# -lt 4 ]
+then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+else
+	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
+	if [ $? -eq 0 ]
+	then
+		echo "FILE WAS TRANSFERED SUCCESSFULLY"
+	else
+		echo "FILE TRANSFER FAILED"
+	fi
 fi
